### ISSUE TITLE
Thanks 

### ISSUE THREAD

**Issue by jessejgm** [nopnop2002/esp-idf-GPS-Repeater#3]
Hi I can parse nmea and send over bluetooth? Not ble. Only bluetooth?

**Comment by nopnop2002** [comment]
Bluretooth has multiple Profiles.

https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles



esp-idf supports some profiles, but not all.

Which profile do you want to use?

**Comment by jessejgm** [comment]
Spp Blu.

**Comment by nopnop2002** [comment]
Bluetooth SPP is easy to use.

Please tell me the nmea receiving app over bluetooth.

**Comment by jessejgm** [comment]
Parse and send nmea sentences over Bluetooth. App Bluetooth gps. App in Google play store

**Comment by nopnop2002** [comment]
Try latest.
I tested with Bluetooth GPS.
https://play.google.com/store/apps/details?id=googoo.android.btgps
